#!/usr/bin/env node
/**
 * Fetches Star Citizen shipmatrix and writes src/data/ships.generated.ts
 * Filter: production_status === 'flight-ready'
 * Run: node scripts/generate-ships.mjs
 */
import { writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const API_URL = 'https://api.star-citizen.wiki/api/shipmatrix/vehicles?per_page=500'
const OUT_PATH = join(__dirname, '..', 'src', 'data', 'ships.generated.ts')

const CARGO_FOCI = new Set([
  'medium freight', 'heavy freight', 'light freight', 'cargo', 'transport',
  'light freight', 'medium cargo', 'heavy cargo'
])
const COMBAT_FOCI = new Set([
  'light fighter', 'heavy fighter', 'medium fighter', 'gunship', 'bomber',
  'interdiction', 'stealth fighter', 'stealth bomber', 'heavy combat fighter'
])
const MEDICAL_FOCI = new Set(['medical', 'support - medical'])
const MINING_FOCI = new Set(['prospecting and mining', 'heavy mining'])

function mapSize(en) {
  if (!en) return undefined
  const s = String(en).toLowerCase()
  if (['small', 'medium', 'large', 'capital'].includes(s)) return s
  return undefined
}

function mapStatus(en) {
  if (!en) return undefined
  const s = String(en).toLowerCase().replace(/\s+/g, '-')
  if (s === 'flight-ready') return 'flight-ready'
  if (s === 'in-concept' || s === 'concept') return 'in-concept'
  if (s === 'production') return 'production'
  return undefined
}

function deriveRoles(api) {
  const typeEn = (api.type?.en_EN || '').toLowerCase()
  const foci = (api.foci || []).map((f) => (f.en_EN || '').toLowerCase())
  const crewMax = api.crew?.max ?? 1
  const roles = new Set()

  if (typeEn === 'transport' || foci.some((f) => CARGO_FOCI.has(f))) roles.add('cargo')
  if (typeEn === 'combat' || foci.some((f) => COMBAT_FOCI.has(f))) roles.add('combat')
  if (foci.some((f) => MEDICAL_FOCI.has(f))) roles.add('medical')
  if (foci.some((f) => MINING_FOCI.has(f))) roles.add('mining')
  if (crewMax >= 2) roles.add('multi-crew')

  if (roles.size === 0) roles.add('cargo')
  return Array.from(roles)
}

function deriveStorageBehavior(api) {
  const sizeEn = (api.size?.en_EN || '').toLowerCase()
  const typeEn = (api.type?.en_EN || '').toLowerCase()
  if (typeEn === 'combat' && sizeEn === 'small') return 'local'
  if (['large', 'capital'].includes(sizeEn) && typeEn === 'transport') return 'ship'
  if (['medium', 'large'].includes(sizeEn)) return 'both'
  return 'both'
}

function mapVehicle(api) {
  const id = api.slug || String(api.id)
  const name = api.name || id
  const status = mapStatus(api.production_status?.en_EN)
  const roles = deriveRoles(api)
  const crewMin = api.crew?.min != null ? api.crew.min : undefined
  const crewMax = api.crew?.max != null ? api.crew.max : undefined
  const cargoScu = api.cargo_capacity != null ? api.cargo_capacity : undefined
  return {
    id,
    name,
    roles,
    storageBehavior: deriveStorageBehavior(api),
    manufacturer: api.manufacturer?.name,
    size: mapSize(api.size?.en_EN),
    status: status || undefined,
    ...(crewMin != null && { crewMin }),
    ...(crewMax != null && { crewMax }),
    ...(cargoScu != null && { cargoScu }),
  }
}

async function main() {
  const res = await fetch(API_URL)
  if (!res.ok) throw new Error(`API ${res.status}: ${res.statusText}`)
  const json = await res.json()
  const list = json.data || json
  const flightReady = list.filter(
    (v) => (v.production_status?.en_EN || '').toLowerCase() === 'flight-ready'
  )
  const mapped = flightReady.map(mapVehicle)

  const lines = [
    '/* eslint-disable @typescript-eslint/no-unused-expressions */',
    '// Generated by scripts/generate-ships.mjs – do not edit by hand',
    "import type { ShipProfile } from './shipTypes'",
    '',
    `export const shipsGenerated: ShipProfile[] = ${JSON.stringify(mapped, null, 2)}`,
    '',
  ]
  writeFileSync(OUT_PATH, lines.join('\n'), 'utf8')
  console.log(`Wrote ${mapped.length} ships to ${OUT_PATH}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
