#!/usr/bin/env node
/**
 * Reads curated "best routes" from data/best-routes.json (or PREFLIGHT_ROUTES_URL)
 * and writes src/data/routes.generated.ts for the app.
 *
 * Run: node scripts/update-routes.mjs
 * Env: PREFLIGHT_ROUTES_URL=<url>  optional URL to fetch JSON instead of local file
 */
import { writeFileSync, readFileSync, existsSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const LOCAL_JSON = join(ROOT, 'data', 'best-routes.json')
const OUT_PATH = join(ROOT, 'src', 'data', 'routes.generated.ts')

function loadLocal() {
  if (!existsSync(LOCAL_JSON)) return []
  const raw = readFileSync(LOCAL_JSON, 'utf8')
  const parsed = JSON.parse(raw)
  if (!Array.isArray(parsed)) return []
  return parsed.filter(
    (r) =>
      r && typeof r === 'object' && typeof r.id === 'string' && typeof r.label === 'string'
  )
}

async function loadFromUrl(url) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Fetch failed: ${res.status}`)
  const parsed = await res.json()
  if (!Array.isArray(parsed)) return []
  return parsed.filter(
    (r) =>
      r && typeof r === 'object' && typeof r.id === 'string' && typeof r.label === 'string'
  )
}

function writeGenerated(routes) {
  const lines = [
    '// Generated by scripts/update-routes.mjs – do not edit by hand',
    '',
    `export const BEST_ROUTES = ${JSON.stringify(routes, null, 2)} as const`,
    ''
  ]
  writeFileSync(OUT_PATH, lines.join('\n'), 'utf8')
  console.log(`Wrote ${routes.length} best routes to ${OUT_PATH}`)
}

async function main() {
  const url = process.env.PREFLIGHT_ROUTES_URL
  const routes = url ? await loadFromUrl(url) : loadLocal()
  writeGenerated(routes)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
