// Generated by scripts/fetch-routes-api.mjs – do not edit by hand

export const BEST_ROUTES = [
  {
    "id": "stanton-loop",
    "label": "Stanton loop",
    "longHaul": true
  },
  {
    "id": "lyria-mining",
    "label": "Lyria mining run"
  },
  {
    "id": "city-trade",
    "label": "City trade route"
  }
] as const
