/* eslint-disable @typescript-eslint/no-unused-expressions */
// Generated by scripts/fetch-ships-api.mjs – do not edit by hand
import type { ShipProfile } from './shipTypes'

export const shipsGenerated: ShipProfile[] = [
  {
    "id": "avenger-stalker",
    "name": "Avenger Stalker",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "avenger-titan",
    "name": "Avenger Titan",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "avenger-titan-renegade",
    "name": "Avenger Titan Renegade",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "avenger-warlock",
    "name": "Avenger Warlock",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "eclipse",
    "name": "Eclipse",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "eclipse",
    "name": "Eclipse",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "gladius",
    "name": "Gladius",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "gladius-dunlevy",
    "name": "Gladius Dunlevy",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "gladius-pirate",
    "name": "Gladius Pirate",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "gladius-valiant",
    "name": "Gladius Valiant",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "hammerhead",
    "name": "Hammerhead",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 40
  },
  {
    "id": "hammerhead-2949-best-in-show-edition",
    "name": "Hammerhead 2949 Best In Show Edition",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 40
  },
  {
    "id": "idris-m",
    "name": "Idris-M",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 1326
  },
  {
    "id": "idris-p",
    "name": "Idris-P",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 1374
  },
  {
    "id": "idris-p",
    "name": "Idris-P",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 1374
  },
  {
    "id": "idris-p-wikelo-war-special",
    "name": "Idris-P Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 1374
  },
  {
    "id": "reclaimer",
    "name": "Reclaimer",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 420
  },
  {
    "id": "reclaimer-2949-best-in-show-edition",
    "name": "Reclaimer 2949 Best In Show Edition",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 420
  },
  {
    "id": "reclaimer-teachs-special",
    "name": "Reclaimer Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 420
  },
  {
    "id": "redeemer",
    "name": "Redeemer",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 4,
    "crewMax": 4,
    "cargoScu": 2
  },
  {
    "id": "retaliator",
    "name": "Retaliator",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "sabre",
    "name": "Sabre",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "sabre-comet",
    "name": "Sabre Comet",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "sabre-firebird",
    "name": "Sabre Firebird",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "sabre-firebird-wikelo-war-special",
    "name": "Sabre Firebird Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "sabre-peregrine",
    "name": "Sabre Peregrine",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "sabre-peregrine-wikelo-speedy-special",
    "name": "Sabre Peregrine Wikelo Speedy Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "sabre-raven",
    "name": "Sabre Raven",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "vanguard-harbinger",
    "name": "Vanguard Harbinger",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "vanguard-hoplite",
    "name": "Vanguard Hoplite",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "vanguard-sentinel",
    "name": "Vanguard Sentinel",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "vanguard-warden",
    "name": "Vanguard Warden",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "arrow",
    "name": "Arrow",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "asgard",
    "name": "Asgard",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 180
  },
  {
    "id": "asgard-wikelo-war-special",
    "name": "Asgard Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 180
  },
  {
    "id": "c8-pisces",
    "name": "C8 Pisces",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "c8r-pisces-rescue",
    "name": "C8R Pisces Rescue",
    "roles": [
      "medical"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "c8x-pisces-expedition",
    "name": "C8X Pisces Expedition",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "carrack",
    "name": "Carrack",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 6,
    "crewMax": 6,
    "cargoScu": 456
  },
  {
    "id": "carrack",
    "name": "Carrack",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 6,
    "crewMax": 6,
    "cargoScu": 456
  },
  {
    "id": "carrack-expedition",
    "name": "Carrack Expedition",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 6,
    "crewMax": 6,
    "cargoScu": 456
  },
  {
    "id": "f7a-hornet-mk-i",
    "name": "F7A Hornet Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f7a-hornet-mk-ii",
    "name": "F7A Hornet Mk II",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f7c-hornet-mk-i",
    "name": "F7C Hornet Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "f7c-hornet-mk-ii",
    "name": "F7C Hornet Mk II",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "f7c-hornet-wildfire-mk-i",
    "name": "F7C Hornet Wildfire Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "f7c-m-hornet-heartseeker-mk-i",
    "name": "F7C-M Hornet Heartseeker Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f7c-m-hornet-heartseeker-mk-ii",
    "name": "F7C-M Hornet Heartseeker Mk II",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "f7c-m-super-hornet-mk-i",
    "name": "F7C-M Super Hornet Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f7c-m-super-hornet-mk-ii",
    "name": "F7C-M Super Hornet Mk II",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "f7c-r-hornet-tracker-mk-i",
    "name": "F7C-R Hornet Tracker Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f7c-r-hornet-tracker-mk-ii",
    "name": "F7C-R Hornet Tracker Mk II",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f7c-s-hornet-ghost-mk-i",
    "name": "F7C-S Hornet Ghost Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f7c-s-hornet-ghost-mk-ii",
    "name": "F7C-S Hornet Ghost Mk II",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f8a-lightning",
    "name": "F8A Lightning",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f8c-lightning",
    "name": "F8C Lightning",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f8c-lightning",
    "name": "F8C Lightning",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f8c-lightning-executive-edition",
    "name": "F8C Lightning Executive Edition",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f8c-lightning-wikelo-sneak-special",
    "name": "F8C Lightning Wikelo Sneak Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f8c-lightning-wikelo-war-special",
    "name": "F8C Lightning Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "gladiator",
    "name": "Gladiator",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "hawk",
    "name": "Hawk",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "hurricane",
    "name": "Hurricane",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "paladin",
    "name": "Paladin",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 4,
    "crewMax": 4,
    "cargoScu": 4
  },
  {
    "id": "terrapin",
    "name": "Terrapin",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "terrapin-medic",
    "name": "Terrapin Medic",
    "roles": [
      "medical"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "terrapin-medic-wikelo-savior-special",
    "name": "Terrapin Medic Wikelo Savior Special",
    "roles": [
      "medical"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "valkyrie",
    "name": "Valkyrie",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 90
  },
  {
    "id": "valkyrie",
    "name": "Valkyrie",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 90
  },
  {
    "id": "khartu-al",
    "name": "Khartu-al",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aopoa",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "santokyai",
    "name": "San'tok.yāi",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aopoa",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "mole",
    "name": "MOLE",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 5,
    "crewMax": 5,
    "cargoScu": 96
  },
  {
    "id": "mole-carbon",
    "name": "MOLE Carbon",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 5,
    "crewMax": 5,
    "cargoScu": 96
  },
  {
    "id": "mole-talus",
    "name": "MOLE Talus",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 5,
    "crewMax": 5,
    "cargoScu": 96
  },
  {
    "id": "mole-teachs-special",
    "name": "MOLE Teach's Special",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 5,
    "crewMax": 5,
    "cargoScu": 96
  },
  {
    "id": "mpuv-cargo",
    "name": "MPUV Cargo",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "mpuv-personnel",
    "name": "MPUV Personnel",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "mpuv-tractor",
    "name": "MPUV Tractor",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 16
  },
  {
    "id": "raft",
    "name": "RAFT",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 192
  },
  {
    "id": "raft-wikelo-work-special",
    "name": "RAFT Wikelo Work Special",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 192
  },
  {
    "id": "srv",
    "name": "SRV",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "defender",
    "name": "Defender",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Banu",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "mustang-alpha",
    "name": "Mustang Alpha",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "mustang-beta",
    "name": "Mustang Beta",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "mustang-citizencon-2948-edition",
    "name": "Mustang CitizenCon 2948 Edition",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "mustang-delta",
    "name": "Mustang Delta",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "mustang-gamma",
    "name": "Mustang Gamma",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "mustang-omega",
    "name": "Mustang Omega",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "nomad",
    "name": "Nomad",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 24
  },
  {
    "id": "nomad-teachs-special",
    "name": "Nomad Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 24
  },
  {
    "id": "corsair-pyam-exec",
    "name": "Corsair PYAM Exec",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 4,
    "crewMax": 4,
    "cargoScu": 72
  },
  {
    "id": "corsair-pyam-exec",
    "name": "Corsair PYAM Exec",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 4,
    "crewMax": 4,
    "cargoScu": 72
  },
  {
    "id": "a1-spirit",
    "name": "A1 Spirit",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "a2-hercules-starlifter",
    "name": "A2 Hercules Starlifter",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 8,
    "crewMax": 8,
    "cargoScu": 1434
  },
  {
    "id": "ares-star-fighter-inferno",
    "name": "Ares Star Fighter Inferno",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "ares-star-fighter-ion",
    "name": "Ares Star Fighter Ion",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Crusader Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "c1-spirit",
    "name": "C1 Spirit",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 64
  },
  {
    "id": "c1-spirit-wikelo-special",
    "name": "C1 Spirit Wikelo Special",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 64
  },
  {
    "id": "c2-hercules-starlifter",
    "name": "C2 Hercules Starlifter",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Crusader Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 1434
  },
  {
    "id": "intrepid",
    "name": "Intrepid",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "intrepid-wikelo-work-special",
    "name": "Intrepid Wikelo Work Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "m2-hercules-starlifter",
    "name": "M2 Hercules Starlifter",
    "roles": [
      "cargo",
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 1434
  },
  {
    "id": "mercury-star-runner",
    "name": "Mercury Star Runner",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 114
  },
  {
    "id": "cutlass-black-pyam-exec",
    "name": "Cutlass Black PYAM Exec",
    "roles": [
      "cargo",
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 46
  },
  {
    "id": "cutlass-black-pyam-exec",
    "name": "Cutlass Black PYAM Exec",
    "roles": [
      "cargo",
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 46
  },
  {
    "id": "buccaneer",
    "name": "Buccaneer",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "caterpillar",
    "name": "Caterpillar",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Drake Interplanetary",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 576
  },
  {
    "id": "caterpillar-pirate",
    "name": "Caterpillar Pirate",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Drake Interplanetary",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 576
  },
  {
    "id": "clipper",
    "name": "Clipper",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "corsair",
    "name": "Corsair",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 4,
    "crewMax": 4,
    "cargoScu": 72
  },
  {
    "id": "cutlass-black",
    "name": "Cutlass Black",
    "roles": [
      "cargo",
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 46
  },
  {
    "id": "cutlass-black",
    "name": "Cutlass Black",
    "roles": [
      "cargo",
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 46
  },
  {
    "id": "cutlass-blue",
    "name": "Cutlass Blue",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 12
  },
  {
    "id": "cutlass-blue",
    "name": "Cutlass Blue",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 12
  },
  {
    "id": "cutlass-red",
    "name": "Cutlass Red",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 12
  },
  {
    "id": "cutlass-red",
    "name": "Cutlass Red",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 12
  },
  {
    "id": "cutlass-steel",
    "name": "Cutlass Steel",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 46
  },
  {
    "id": "cutter",
    "name": "Cutter",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "cutter-rambler",
    "name": "Cutter Rambler",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "cutter-scout",
    "name": "Cutter Scout",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "golem",
    "name": "Golem",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "golem-ox",
    "name": "Golem OX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 64
  },
  {
    "id": "golem-teachs-special",
    "name": "Golem Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "golem-wikelo-work-special",
    "name": "Golem Wikelo Work Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "herald",
    "name": "Herald",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "vulture",
    "name": "Vulture",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "vulture-teachs-special",
    "name": "Vulture Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "blade",
    "name": "Blade",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Esperia",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "glaive",
    "name": "Glaive",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Esperia",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "prowler",
    "name": "Prowler",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Esperia",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "prowler-utility",
    "name": "Prowler Utility",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Esperia",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "prowler-utility-wikelo-work-special",
    "name": "Prowler Utility Wikelo Work Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Esperia",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "esperia-stinger",
    "name": "Esperia Stinger",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Vanduul",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.9
  },
  {
    "id": "talon",
    "name": "Talon",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Esperia",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "talon-shrike",
    "name": "Talon Shrike",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Esperia",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f8c-lightning-pyam-exec",
    "name": "F8C Lightning PYAM Exec",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "f8c-lightning-pyam-exec",
    "name": "F8C Lightning PYAM Exec",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "syulen",
    "name": "Syulen",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Gatac Manufacture",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "shiv",
    "name": "Shiv",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Grey's Market",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "l-21-wolf",
    "name": "L-21 Wolf",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Kruger Intergalatic",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "l-21-wolf-wikelo-sneak-special",
    "name": "L-21 Wolf Wikelo Sneak Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Kruger Intergalatic",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "l-21-wolf-wikelo-war-special",
    "name": "L-21 Wolf Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Kruger Intergalatic",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "l-22-alpha-wolf",
    "name": "L-22 Alpha Wolf",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Kruger Intergalatic",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "p-52-merlin",
    "name": "P-52 Merlin",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Kruger Intergalatic",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "p-72-archimedes",
    "name": "P-72 Archimedes",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Kruger Intergalatic",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "p-72-archimedes-emerald",
    "name": "P-72 Archimedes Emerald",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Kruger Intergalatic",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "fury",
    "name": "Fury",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "fury-lx",
    "name": "Fury LX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "fury-mx",
    "name": "Fury MX",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "guardian",
    "name": "Guardian",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "guardian-mx",
    "name": "Guardian MX",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "guardian-mx-wikelo-war-special",
    "name": "Guardian MX Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "guardian-qi",
    "name": "Guardian QI",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "guardian-qi-wikelo-special",
    "name": "Guardian QI Wikelo Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "guardian-wikelo-war-special",
    "name": "Guardian Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "razor",
    "name": "Razor",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "razor-ex",
    "name": "Razor EX",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "razor-lx",
    "name": "Razor LX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "fortune",
    "name": "Fortune",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 16
  },
  {
    "id": "fortune-teachs-special",
    "name": "Fortune Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 16
  },
  {
    "id": "fortune-wikelo-special",
    "name": "Fortune Wikelo Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 16
  },
  {
    "id": "freelancer",
    "name": "Freelancer",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 66
  },
  {
    "id": "freelancer-dur",
    "name": "Freelancer DUR",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 36
  },
  {
    "id": "freelancer-max",
    "name": "Freelancer MAX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 120
  },
  {
    "id": "freelancer-mis",
    "name": "Freelancer MIS",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 36
  },
  {
    "id": "hull-a",
    "name": "Hull A",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 64
  },
  {
    "id": "hull-c",
    "name": "Hull C",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4608
  },
  {
    "id": "prospector",
    "name": "Prospector",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "prospector-wikelo-work-special",
    "name": "Prospector Wikelo Work Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "reliant-kore",
    "name": "Reliant Kore",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "reliant-mako",
    "name": "Reliant Mako",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "reliant-sen",
    "name": "Reliant Sen",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "reliant-tana",
    "name": "Reliant Tana",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "starfarer",
    "name": "Starfarer",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 291
  },
  {
    "id": "starfarer-gemini",
    "name": "Starfarer Gemini",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 291
  },
  {
    "id": "starfarer-teachs-special",
    "name": "Starfarer Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 291
  },
  {
    "id": "starlancer-max",
    "name": "Starlancer MAX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 224
  },
  {
    "id": "starlancer-max-wikelo-work-special",
    "name": "Starlancer MAX Wikelo Work Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 224
  },
  {
    "id": "starlancer-tac",
    "name": "Starlancer TAC",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 96
  },
  {
    "id": "starlancer-tac-wikelo-war-special",
    "name": "Starlancer TAC Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 96
  },
  {
    "id": "100i",
    "name": "100i",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "125a",
    "name": "125a",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "135c",
    "name": "135c",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "300i",
    "name": "300i",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "315p",
    "name": "315p",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "325a",
    "name": "325a",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "350r",
    "name": "350r",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "400i",
    "name": "400i",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 42
  },
  {
    "id": "600i",
    "name": "600i",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 44
  },
  {
    "id": "600i-2951-bis",
    "name": "600i 2951 BIS",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 44
  },
  {
    "id": "600i-executive-edition",
    "name": "600i Executive Edition",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 44
  },
  {
    "id": "600i-touring",
    "name": "600i Touring",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 38
  },
  {
    "id": "85x-limited",
    "name": "85X Limited",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "890-jump",
    "name": "890 Jump",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 388
  },
  {
    "id": "m50-interceptor",
    "name": "M50 Interceptor",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "apollo-medivac",
    "name": "Apollo Medivac",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "apollo-medivac",
    "name": "Apollo Medivac",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "apollo-medivac",
    "name": "Apollo Medivac",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "apollo-medivac",
    "name": "Apollo Medivac",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "apollo-triage",
    "name": "Apollo Triage",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "apollo-triage",
    "name": "Apollo Triage",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "apollo-triage",
    "name": "Apollo Triage",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "apollo-triage",
    "name": "Apollo Triage",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "aurora-cl",
    "name": "Aurora CL",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "aurora-es",
    "name": "Aurora ES",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 3
  },
  {
    "id": "aurora-ln",
    "name": "Aurora LN",
    "roles": [
      "cargo",
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 3
  },
  {
    "id": "aurora-lx",
    "name": "Aurora LX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 3
  },
  {
    "id": "aurora-mr",
    "name": "Aurora MR",
    "roles": [
      "cargo",
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 3
  },
  {
    "id": "constellation-andromeda",
    "name": "Constellation Andromeda",
    "roles": [
      "cargo",
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 96
  },
  {
    "id": "constellation-aquila",
    "name": "Constellation Aquila",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 96
  },
  {
    "id": "constellation-phoenix",
    "name": "Constellation Phoenix",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 176
  },
  {
    "id": "constellation-phoenix-emerald",
    "name": "Constellation Phoenix Emerald",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 80
  },
  {
    "id": "constellation-taurus",
    "name": "Constellation Taurus",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 270
  },
  {
    "id": "constellation-taurus-wikelo-war-special",
    "name": "Constellation Taurus Wikelo War Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 270
  },
  {
    "id": "hermes",
    "name": "Hermes",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 288
  },
  {
    "id": "mantis",
    "name": "Mantis",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "meteor",
    "name": "Meteor",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "meteor-pyam-exec",
    "name": "Meteor PYAM Exec",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "meteor-wikelo-sneak-special",
    "name": "Meteor Wikelo Sneak Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "perseus",
    "name": "Perseus",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 6,
    "crewMax": 6,
    "cargoScu": 96
  },
  {
    "id": "polaris",
    "name": "Polaris",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 12,
    "crewMax": 12,
    "cargoScu": 576
  },
  {
    "id": "polaris",
    "name": "Polaris",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 12,
    "crewMax": 12,
    "cargoScu": 576
  },
  {
    "id": "salvation",
    "name": "Salvation",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "scorpius",
    "name": "Scorpius",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "scorpius-antares",
    "name": "Scorpius Antares",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "scorpius-wikelo-sneak-special",
    "name": "Scorpius Wikelo Sneak Special",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "zeus-mk-ii-cl",
    "name": "Zeus Mk II CL",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 128
  },
  {
    "id": "zeus-mk-ii-cl",
    "name": "Zeus Mk II CL",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 128
  },
  {
    "id": "zeus-mk-ii-es",
    "name": "Zeus Mk II ES",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 32
  },
  {
    "id": "zeus-mk-ii-es-wikelo-work-special",
    "name": "Zeus Mk II ES Wikelo Work Special",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 32
  },
  {
    "id": "syulen-pyam-exec",
    "name": "Syulen PYAM Exec",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Gatac Manufacture",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "syulen-pyam-exec",
    "name": "Syulen PYAM Exec",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Gatac Manufacture",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "vanduul-scythe",
    "name": "Vanduul Scythe",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Esperia",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  }
]
