/* eslint-disable @typescript-eslint/no-unused-expressions */
// Generated by scripts/fetch-ships-api.mjs – do not edit by hand
import type { ShipProfile } from './shipTypes'

export const shipsGenerated: ShipProfile[] = [
  {
    "id": "aegs-avenger-stalker",
    "name": "Avenger Stalker",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "aegs-avenger-titan",
    "name": "Avenger Titan",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "aegs-avenger-titan-renegade",
    "name": "Avenger Titan Renegade",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "aegs-avenger-warlock",
    "name": "Avenger Warlock",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "aegs-eclipse-bis2950",
    "name": "Eclipse",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-eclipse",
    "name": "Eclipse",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-gladius",
    "name": "Gladius",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-gladius-dunlevy",
    "name": "Gladius Dunlevy",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-gladius-pir",
    "name": "Gladius Pirate",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-gladius-valiant",
    "name": "Gladius Valiant",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-hammerhead",
    "name": "Hammerhead",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 40
  },
  {
    "id": "aegs-hammerhead-showdown",
    "name": "Hammerhead 2949 Best In Show Edition",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 40
  },
  {
    "id": "aegs-idris-m",
    "name": "Idris-M",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 1326
  },
  {
    "id": "aegs-idris-p",
    "name": "Idris-P",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 1374
  },
  {
    "id": "aegs-idris-p-fw-25",
    "name": "Idris-P",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 1374
  },
  {
    "id": "aegs-idris-p-collector-military",
    "name": "Idris-P Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 1374
  },
  {
    "id": "aegs-reclaimer",
    "name": "Reclaimer",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 420
  },
  {
    "id": "aegs-reclaimer-showdown",
    "name": "Reclaimer 2949 Best In Show Edition",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 420
  },
  {
    "id": "aegs-reclaimer-teach",
    "name": "Reclaimer Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 420
  },
  {
    "id": "aegs-redeemer",
    "name": "Redeemer",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 4,
    "crewMax": 4,
    "cargoScu": 2
  },
  {
    "id": "aegs-retaliator",
    "name": "Retaliator",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "aegs-sabre",
    "name": "Sabre",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-sabre-comet",
    "name": "Sabre Comet",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-sabre-firebird",
    "name": "Sabre Firebird",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-sabre-firebird-collector-milt",
    "name": "Sabre Firebird Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-sabre-peregrine",
    "name": "Sabre Peregrine",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-sabre-peregrine-collector-competition",
    "name": "Sabre Peregrine Wikelo Speedy Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-sabre-raven",
    "name": "Sabre Raven",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-vanguard-harbinger",
    "name": "Vanguard Harbinger",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-vanguard-hoplite",
    "name": "Vanguard Hoplite",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-vanguard-sentinel",
    "name": "Vanguard Sentinel",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-vanguard",
    "name": "Vanguard Warden",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-arrow",
    "name": "Arrow",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-asgard",
    "name": "Asgard",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 180
  },
  {
    "id": "anvl-asgard-collector-military",
    "name": "Asgard Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 180
  },
  {
    "id": "anvl-c8-pisces",
    "name": "C8 Pisces",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "anvl-c8r-pisces",
    "name": "C8R Pisces Rescue",
    "roles": [
      "medical"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-c8x-pisces-expedition",
    "name": "C8X Pisces Expedition",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "anvl-carrack",
    "name": "Carrack",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 6,
    "crewMax": 6,
    "cargoScu": 456
  },
  {
    "id": "anvl-carrack-bis2950",
    "name": "Carrack",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 6,
    "crewMax": 6,
    "cargoScu": 456
  },
  {
    "id": "anvl-carrack-expedition",
    "name": "Carrack Expedition",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 6,
    "crewMax": 6,
    "cargoScu": 456
  },
  {
    "id": "anvl-hornet-f7a-mk1",
    "name": "F7A Hornet Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7a-mk2",
    "name": "F7A Hornet Mk II",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7c",
    "name": "F7C Hornet Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7c-mk2",
    "name": "F7C Hornet Mk II",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "anvl-hornet-f7c-wildfire",
    "name": "F7C Hornet Wildfire Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7cm-heartseeker",
    "name": "F7C-M Hornet Heartseeker Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7cm-mk2-heartseeker",
    "name": "F7C-M Hornet Heartseeker Mk II",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7cm",
    "name": "F7C-M Super Hornet Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7cm-mk2",
    "name": "F7C-M Super Hornet Mk II",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7cr",
    "name": "F7C-R Hornet Tracker Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7cr-mk2",
    "name": "F7C-R Hornet Tracker Mk II",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7cs",
    "name": "F7C-S Hornet Ghost Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7cs-mk2",
    "name": "F7C-S Hornet Ghost Mk II",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-lightning-f8",
    "name": "F8A Lightning",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-lightning-f8c",
    "name": "F8C Lightning",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-lightning-f8c-plat",
    "name": "F8C Lightning",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-lightning-f8c-exec",
    "name": "F8C Lightning Executive Edition",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-lightning-f8c-collector-stealth",
    "name": "F8C Lightning Wikelo Sneak Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-lightning-f8c-collector-military",
    "name": "F8C Lightning Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-gladiator",
    "name": "Gladiator",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hawk",
    "name": "Hawk",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hurricane",
    "name": "Hurricane",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-paladin",
    "name": "Paladin",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 4,
    "crewMax": 4,
    "cargoScu": 4
  },
  {
    "id": "anvl-terrapin",
    "name": "Terrapin",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-terrapin-medic",
    "name": "Terrapin Medic",
    "roles": [
      "medical"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-terrapin-medic-collector-medic",
    "name": "Terrapin Medic Wikelo Savior Special",
    "roles": [
      "medical"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-valkyrie-bis2950",
    "name": "Valkyrie",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 90
  },
  {
    "id": "anvl-valkyrie",
    "name": "Valkyrie",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 90
  },
  {
    "id": "xian-scout",
    "name": "Khartu-al",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aopoa",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "xnaa-santokyai",
    "name": "San'tok.yāi",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aopoa",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "argo-mole",
    "name": "MOLE",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 5,
    "crewMax": 5,
    "cargoScu": 32
  },
  {
    "id": "argo-mole-teach",
    "name": "MOLE Teach's Special",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 5,
    "crewMax": 5,
    "cargoScu": 32
  },
  {
    "id": "argo-moth",
    "name": "MOTH",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 224
  },
  {
    "id": "argo-mpuv",
    "name": "MPUV Cargo",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "argo-mpuv-transport",
    "name": "MPUV Personnel",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "argo-mpuv-1t",
    "name": "MPUV Tractor",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 16
  },
  {
    "id": "argo-raft",
    "name": "RAFT",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 192
  },
  {
    "id": "argo-raft-collector-indust",
    "name": "RAFT Wikelo Work Special",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 192
  },
  {
    "id": "argo-srv",
    "name": "SRV",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Argo Astronautics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "banu-defender",
    "name": "Defender",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Banu",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "cnou-mustang-alpha",
    "name": "Mustang Alpha",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "cnou-mustang-beta",
    "name": "Mustang Beta",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "cnou-mustang-alpha-citizencon2018",
    "name": "Mustang CitizenCon 2948 Edition",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "cnou-mustang-delta",
    "name": "Mustang Delta",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "cnou-mustang-gamma",
    "name": "Mustang Gamma",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "cnou-mustang-omega",
    "name": "Mustang Omega",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "cnou-nomad",
    "name": "Nomad",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 24
  },
  {
    "id": "cnou-nomad-teach",
    "name": "Nomad Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Consolidated Outland",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 24
  },
  {
    "id": "drak-corsair-exec-military",
    "name": "Corsair PYAM Exec",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 4,
    "crewMax": 4,
    "cargoScu": 72
  },
  {
    "id": "drak-corsair-exec-stealthindustrial",
    "name": "Corsair PYAM Exec",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 4,
    "crewMax": 4,
    "cargoScu": 72
  },
  {
    "id": "crus-spirit-a1",
    "name": "A1 Spirit",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "crus-starlifter-a2",
    "name": "A2 Hercules Starlifter",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 8,
    "crewMax": 8,
    "cargoScu": 1434
  },
  {
    "id": "crus-starfighter-inferno",
    "name": "Ares Star Fighter Inferno",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "crus-starfighter-ion",
    "name": "Ares Star Fighter Ion",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Crusader Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "crus-spirit-c1",
    "name": "C1 Spirit",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 64
  },
  {
    "id": "crus-spirit-c1-civilian",
    "name": "C1 Spirit Wikelo Special",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 64
  },
  {
    "id": "crus-starlifter-c2",
    "name": "C2 Hercules Starlifter",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Crusader Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 1434
  },
  {
    "id": "crus-intrepid",
    "name": "Intrepid",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "crus-intrepid-collector-indust",
    "name": "Intrepid Wikelo Work Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "crus-starlifter-m2",
    "name": "M2 Hercules Starlifter",
    "roles": [
      "cargo",
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 1434
  },
  {
    "id": "crus-star-runner",
    "name": "Mercury Star Runner",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Crusader Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 114
  },
  {
    "id": "drak-cutlass-black-exec-military",
    "name": "Cutlass Black PYAM Exec",
    "roles": [
      "cargo",
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 46
  },
  {
    "id": "drak-cutlass-black-exec-stealth",
    "name": "Cutlass Black PYAM Exec",
    "roles": [
      "cargo",
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 46
  },
  {
    "id": "drak-buccaneer",
    "name": "Buccaneer",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "drak-caterpillar",
    "name": "Caterpillar",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Drake Interplanetary",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 576
  },
  {
    "id": "drak-caterpillar-boarded",
    "name": "Caterpillar",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Drake Interplanetary",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 576
  },
  {
    "id": "drak-caterpillar-pirate",
    "name": "Caterpillar Pirate",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Drake Interplanetary",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 576
  },
  {
    "id": "drak-clipper",
    "name": "Clipper",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "drak-corsair",
    "name": "Corsair",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 4,
    "crewMax": 4,
    "cargoScu": 72
  },
  {
    "id": "drak-cutlass-black-bis2950",
    "name": "Cutlass Black",
    "roles": [
      "cargo",
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 46
  },
  {
    "id": "drak-cutlass-black",
    "name": "Cutlass Black",
    "roles": [
      "cargo",
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 46
  },
  {
    "id": "drak-cutlass-blue",
    "name": "Cutlass Blue",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 12
  },
  {
    "id": "drak-cutlass-blue-bis2950",
    "name": "Cutlass Blue",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 12
  },
  {
    "id": "drak-cutlass-red",
    "name": "Cutlass Red",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 12
  },
  {
    "id": "drak-cutlass-red-bis2950",
    "name": "Cutlass Red",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 12
  },
  {
    "id": "drak-cutlass-steel",
    "name": "Cutlass Steel",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 46
  },
  {
    "id": "drak-cutter",
    "name": "Cutter",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "drak-cutter-rambler",
    "name": "Cutter Rambler",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "drak-cutter-scout",
    "name": "Cutter Scout",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "drak-golem",
    "name": "Golem",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "drak-golem-ox",
    "name": "Golem OX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 64
  },
  {
    "id": "drak-golem-teach",
    "name": "Golem Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "drak-golem-collector-indust",
    "name": "Golem Wikelo Work Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "drak-herald",
    "name": "Herald",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "drak-vulture",
    "name": "Vulture",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "drak-vulture-teach",
    "name": "Vulture Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Drake Interplanetary",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "vncl-blade",
    "name": "Blade",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Esperia",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "vncl-glaive",
    "name": "Glaive",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Esperia",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "espr-prowler",
    "name": "Prowler",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Esperia",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "espr-prowler-utility",
    "name": "Prowler Utility",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Esperia",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "espr-prowler-utility-collector-indust",
    "name": "Prowler Utility Wikelo Work Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Esperia",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "vncl-stinger",
    "name": "Esperia Stinger",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Vanduul",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.9
  },
  {
    "id": "espr-talon",
    "name": "Talon",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Esperia",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "espr-talon-shrike",
    "name": "Talon Shrike",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Esperia",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-lightning-f8c-exec-stealth",
    "name": "F8C Lightning PYAM Exec",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-lightning-f8c-exec-military",
    "name": "F8C Lightning PYAM Exec",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "gama-syulen",
    "name": "Syulen",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Gatac Manufacture",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "glsn-shiv",
    "name": "Shiv",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Grey's Market",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "krig-l21-wolf",
    "name": "L-21 Wolf",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Kruger Intergalatic",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "krig-l21-wolf-collector-stealth",
    "name": "L-21 Wolf Wikelo Sneak Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Kruger Intergalatic",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "krig-l21-wolf-collector-military",
    "name": "L-21 Wolf Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Kruger Intergalatic",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "krig-l22-alphawolf",
    "name": "L-22 Alpha Wolf",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Kruger Intergalatic",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "krig-p52-merlin",
    "name": "P-52 Merlin",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Kruger Intergalatic",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "krig-p72-archimedes",
    "name": "P-72 Archimedes",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Kruger Intergalatic",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "krig-p72-archimedes-emerald",
    "name": "P-72 Archimedes Emerald",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Kruger Intergalatic",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "misc-fury",
    "name": "Fury",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "misc-fury-lx",
    "name": "Fury LX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "misc-fury-miru",
    "name": "Fury MX",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "mrai-guardian",
    "name": "Guardian",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "mrai-guardian-mx",
    "name": "Guardian MX",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "mrai-guardian-mx-collector-military",
    "name": "Guardian MX Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "mrai-guardian-qi",
    "name": "Guardian QI",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "mrai-guardian-qi-collector-indust",
    "name": "Guardian QI Wikelo Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "mrai-guardian-military",
    "name": "Guardian Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0.65
  },
  {
    "id": "misc-razor",
    "name": "Razor",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "misc-razor-ex",
    "name": "Razor EX",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "misc-razor-lx",
    "name": "Razor LX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Mirai",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "misc-fortune",
    "name": "Fortune",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 16
  },
  {
    "id": "misc-fortune-teach",
    "name": "Fortune Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 16
  },
  {
    "id": "misc-fortune-collector-industrial",
    "name": "Fortune Wikelo Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 16
  },
  {
    "id": "misc-freelancer",
    "name": "Freelancer",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 66
  },
  {
    "id": "misc-freelancer-dur",
    "name": "Freelancer DUR",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 36
  },
  {
    "id": "misc-freelancer-max",
    "name": "Freelancer MAX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 120
  },
  {
    "id": "misc-freelancer-mis",
    "name": "Freelancer MIS",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 36
  },
  {
    "id": "misc-hull-a",
    "name": "Hull A",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 64
  },
  {
    "id": "misc-hull-b",
    "name": "Hull B",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 512
  },
  {
    "id": "misc-hull-c",
    "name": "Hull C",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4608
  },
  {
    "id": "misc-prospector",
    "name": "Prospector",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "misc-prospector-collector-indust",
    "name": "Prospector Wikelo Work Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 32
  },
  {
    "id": "misc-reliant",
    "name": "Reliant Kore",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "misc-reliant-mako",
    "name": "Reliant Mako",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "misc-reliant-sen",
    "name": "Reliant Sen",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "misc-reliant-tana",
    "name": "Reliant Tana",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "misc-starfarer",
    "name": "Starfarer",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 291
  },
  {
    "id": "misc-starfarer-gemini",
    "name": "Starfarer Gemini",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 291
  },
  {
    "id": "misc-starfarer-teach",
    "name": "Starfarer Teach's Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 291
  },
  {
    "id": "misc-starlancer-max",
    "name": "Starlancer MAX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 224
  },
  {
    "id": "misc-starlancer-max-collector-indust",
    "name": "Starlancer MAX Wikelo Work Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 224
  },
  {
    "id": "misc-starlancer-tac",
    "name": "Starlancer TAC",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 96
  },
  {
    "id": "misc-starlancer-tac-collector-military",
    "name": "Starlancer TAC Wikelo War Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Musashi Industrial & Starflight Concern",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 96
  },
  {
    "id": "orig-100i",
    "name": "100i",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "orig-125a",
    "name": "125a",
    "roles": [
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "orig-135c",
    "name": "135c",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "orig-300i",
    "name": "300i",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "orig-315p",
    "name": "315p",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 12
  },
  {
    "id": "orig-325a",
    "name": "325a",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "orig-350r",
    "name": "350r",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "orig-400i",
    "name": "400i",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 42
  },
  {
    "id": "orig-600i",
    "name": "600i",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 44
  },
  {
    "id": "orig-600i-bis2951",
    "name": "600i 2951 BIS",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 44
  },
  {
    "id": "orig-600i-executive-edition",
    "name": "600i Executive Edition",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 44
  },
  {
    "id": "orig-600i-touring",
    "name": "600i Touring",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 38
  },
  {
    "id": "orig-85x",
    "name": "85X Limited",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "orig-890jump",
    "name": "890 Jump",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 388
  },
  {
    "id": "orig-m50",
    "name": "M50 Interceptor",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Origin Jumpworks",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "rsi-apollo-medivac",
    "name": "Apollo Medivac",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "rsi-apollo-medivac-tier-3",
    "name": "Apollo Medivac",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "rsi-apollo-medivac-tier-1",
    "name": "Apollo Medivac",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "rsi-apollo-medivac-tier-2",
    "name": "Apollo Medivac",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "rsi-apollo-triage",
    "name": "Apollo Triage",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "rsi-apollo-triage-tier-1",
    "name": "Apollo Triage",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "rsi-apollo-triage-tier-2",
    "name": "Apollo Triage",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "rsi-apollo-triage-tier-3",
    "name": "Apollo Triage",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "rsi-apollo-triage-collector-stealth",
    "name": "Apollo Triage Wikelo Sneak Special",
    "roles": [
      "medical",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 32
  },
  {
    "id": "rsi-aurora-gs-cl",
    "name": "Aurora Mk I CL",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "rsi-aurora-gs-es",
    "name": "Aurora Mk I ES",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 3
  },
  {
    "id": "rsi-aurora-mk2",
    "name": "Aurora Mk II",
    "roles": [
      "cargo",
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "rsi-aurora-gs-ln",
    "name": "Aurora Mk I LN",
    "roles": [
      "cargo",
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 3
  },
  {
    "id": "rsi-aurora-gs-lx",
    "name": "Aurora Mk I LX",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 3
  },
  {
    "id": "rsi-aurora-gs-mr",
    "name": "Aurora Mk I MR",
    "roles": [
      "cargo",
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 3
  },
  {
    "id": "rsi-aurora-gs-se",
    "name": "Aurora Mk I SE",
    "roles": [
      "cargo",
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "rsi-constellation-andromeda",
    "name": "Constellation Andromeda",
    "roles": [
      "cargo",
      "combat"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 96
  },
  {
    "id": "rsi-constellation-aquila",
    "name": "Constellation Aquila",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 96
  },
  {
    "id": "rsi-constellation-phoenix",
    "name": "Constellation Phoenix",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 80
  },
  {
    "id": "rsi-constellation-phoenix-emerald",
    "name": "Constellation Phoenix Emerald",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 80
  },
  {
    "id": "rsi-constellation-taurus",
    "name": "Constellation Taurus",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 174
  },
  {
    "id": "rsi-constellation-taurus-military",
    "name": "Constellation Taurus Wikelo War Special",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "ship",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 174
  },
  {
    "id": "rsi-hermes",
    "name": "Hermes",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 288
  },
  {
    "id": "rsi-mantis",
    "name": "Mantis",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "rsi-meteor",
    "name": "Meteor",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "rsi-meteor-collector-military",
    "name": "Meteor PYAM Exec",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "rsi-meteor-collector-stealth",
    "name": "Meteor Wikelo Sneak Special",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "rsi-perseus",
    "name": "Perseus",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 6,
    "crewMax": 6,
    "cargoScu": 96
  },
  {
    "id": "rsi-polaris-collector-military",
    "name": "Polaris",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 12,
    "crewMax": 12,
    "cargoScu": 576
  },
  {
    "id": "rsi-polaris",
    "name": "Polaris",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 12,
    "crewMax": 12,
    "cargoScu": 576
  },
  {
    "id": "rsi-salvation",
    "name": "Salvation",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "rsi-scorpius",
    "name": "Scorpius",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "rsi-scorpius-antares",
    "name": "Scorpius Antares",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "rsi-scorpius-stealth",
    "name": "Scorpius Wikelo Sneak Special",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Roberts Space Industries",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "rsi-zeus-cl-collector-indust",
    "name": "Zeus Mk II CL",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 128
  },
  {
    "id": "rsi-zeus-cl",
    "name": "Zeus Mk II CL",
    "roles": [
      "cargo",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 128
  },
  {
    "id": "rsi-zeus-es",
    "name": "Zeus Mk II ES",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 32
  },
  {
    "id": "rsi-zeus-es-collector-indust",
    "name": "Zeus Mk II ES Wikelo Work Special",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Roberts Space Industries",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 3,
    "crewMax": 3,
    "cargoScu": 32
  },
  {
    "id": "gama-syulen-exec-stealth",
    "name": "Syulen PYAM Exec",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Gatac Manufacture",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "gama-syulen-exec-military",
    "name": "Syulen PYAM Exec",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Gatac Manufacture",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 6
  },
  {
    "id": "vncl-scythe",
    "name": "Vanduul Scythe",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Esperia",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  }
]
