/* eslint-disable @typescript-eslint/no-unused-expressions */
// Generated by scripts/fetch-ships-api.mjs – do not edit by hand
import type { ShipProfile } from './shipTypes'

export const shipsGenerated: ShipProfile[] = [
  {
    "id": "aegs-avenger-stalker",
    "name": "Avenger Stalker",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-avenger-titan",
    "name": "Avenger Titan",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "aegs-avenger-titan-renegade",
    "name": "Avenger Titan Renegade",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 8
  },
  {
    "id": "aegs-avenger-warlock",
    "name": "Avenger Warlock",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-eclipse-bis2950",
    "name": "Eclipse",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-eclipse",
    "name": "Eclipse",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-gladius",
    "name": "Gladius",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-gladius-pir",
    "name": "Gladius Pirate",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-gladius-valiant",
    "name": "Gladius Valiant",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-hammerhead",
    "name": "Hammerhead",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 9,
    "crewMax": 11,
    "cargoScu": 40
  },
  {
    "id": "aegs-hammerhead-gs",
    "name": "Hammerhead",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 8,
    "crewMax": 8,
    "cargoScu": 64
  },
  {
    "id": "aegs-hammerhead-showdown",
    "name": "Hammerhead 2949 Best In Show Edition",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 9,
    "crewMax": 11,
    "cargoScu": 0
  },
  {
    "id": "aegs-idris-m",
    "name": "Idris-M",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 28,
    "crewMax": 22,
    "cargoScu": 1326
  },
  {
    "id": "aegs-idris-p",
    "name": "Idris-P",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 28,
    "crewMax": 22,
    "cargoScu": 1374
  },
  {
    "id": "aegs-idris-p-fw-25",
    "name": "Idris-P",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 28,
    "crewMax": 22,
    "cargoScu": 1374
  },
  {
    "id": "aegs-idris-p-tsg",
    "name": "Idris-P",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 28,
    "crewMax": 21,
    "cargoScu": 1374
  },
  {
    "id": "aegs-reclaimer",
    "name": "Reclaimer",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "capital",
    "status": "flight-ready",
    "crewMin": 5,
    "crewMax": 12,
    "cargoScu": 420
  },
  {
    "id": "aegs-reclaimer-showdown",
    "name": "Reclaimer 2949 Best In Show Edition",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 5,
    "crewMax": 12,
    "cargoScu": 420
  },
  {
    "id": "aegs-redeemer",
    "name": "Redeemer",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 4,
    "crewMax": 13,
    "cargoScu": 2
  },
  {
    "id": "aegs-retaliator",
    "name": "Retaliator",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 7,
    "crewMax": 12,
    "cargoScu": 0
  },
  {
    "id": "aegs-sabre",
    "name": "Sabre",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-sabre-comet",
    "name": "Sabre Comet",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-sabre-firebird",
    "name": "Sabre Firebird",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-sabre-peregrine",
    "name": "Sabre Peregrine",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-sabre-raven",
    "name": "Sabre Raven",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Aegis Dynamics",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "aegs-tiburon",
    "name": "Tiburon",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 7,
    "crewMax": 7,
    "cargoScu": 64
  },
  {
    "id": "aegs-vanguard-harbinger",
    "name": "Vanguard Harbinger",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 4,
    "cargoScu": 0
  },
  {
    "id": "aegs-vanguard-hoplite",
    "name": "Vanguard Hoplite",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "aegs-vanguard-sentinel",
    "name": "Vanguard Sentinel",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 5,
    "cargoScu": 0
  },
  {
    "id": "aegs-vanguard",
    "name": "Vanguard Warden",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Aegis Dynamics",
    "size": "medium",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 5,
    "cargoScu": 0
  },
  {
    "id": "anvl-arrow",
    "name": "Arrow",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-asgard",
    "name": "Asgard",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 180
  },
  {
    "id": "anvl-c8-pisces",
    "name": "C8 Pisces",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "anvl-c8r-pisces",
    "name": "C8R Pisces Rescue",
    "roles": [
      "medical"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-c8x-pisces-expedition",
    "name": "C8X Pisces Expedition",
    "roles": [
      "cargo"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 4
  },
  {
    "id": "anvl-carrack",
    "name": "Carrack",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 6,
    "crewMax": 12,
    "cargoScu": 456
  },
  {
    "id": "anvl-carrack-bis2950",
    "name": "Carrack",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 6,
    "crewMax": 12,
    "cargoScu": 456
  },
  {
    "id": "anvl-carrack-expedition",
    "name": "Carrack Expedition",
    "roles": [
      "multi-crew"
    ],
    "storageBehavior": "both",
    "manufacturer": "Anvil Aerospace",
    "size": "large",
    "status": "flight-ready",
    "crewMin": 6,
    "crewMax": 12,
    "cargoScu": 456
  },
  {
    "id": "anvl-hornet-f7a-mk1",
    "name": "F7A Hornet Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7a-mk2",
    "name": "F7A Hornet Mk II",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7c",
    "name": "F7C Hornet Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7c-mk2",
    "name": "F7C Hornet Mk II",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 2
  },
  {
    "id": "anvl-hornet-f7c-wildfire",
    "name": "F7C Hornet Wildfire Mk I",
    "roles": [
      "combat"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 1,
    "crewMax": 1,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7cm-heartseeker",
    "name": "F7C-M Hornet Heartseeker Mk I",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  },
  {
    "id": "anvl-hornet-f7cm-mk2-heartseeker",
    "name": "F7C-M Hornet Heartseeker Mk II",
    "roles": [
      "combat",
      "multi-crew"
    ],
    "storageBehavior": "local",
    "manufacturer": "Anvil Aerospace",
    "size": "small",
    "status": "flight-ready",
    "crewMin": 2,
    "crewMax": 2,
    "cargoScu": 0
  }
]
